// import "./modules/header-menu";
import "./modules/custom-select";
import "./modules/y-maps-opener";
import "./modules/yMaps";
import "./modules/yMapModal";
import "./modules/lw-multiple-checker";
import "./modules/lw-object-list";
import "./modules/lw-fw-btn";
import "./modules/swiper";
import "./modules/collapsed-block";
import "./modules/text-truncate-expand";
import "./modules/mobile-menu";
import "./modules/modal";
